language: ruby
rvm:
 - 2.3
branches:
  only:
    - master
services:
  - postgresql
script:
  - export RAILS_ENV=test
  - bundle exec rake db:schema:load --trace
  - bundle exec rspec spec/
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
